### ISSUE TITLE
Trial commands !scrim and !live

### ISSUE THREAD

**Issue by Nikkijorie** [FMS-by-Conexoes-Games/discord-server#11]
I was making some tests on trial scrims.

When I use the !scrims trial solo arena it doesn't send the "New scrim" embed on the PT channel, only on ES channel. 

When I use the !live trial solo arena it didn't send the "el scrim ha empezado" on ES channel, only on PT channel.

**Comment by eduardozgz** [comment]
That was probably a discord issue, I'm closing this unless this happens again
