### ISSUE TITLE
Check Techz0r code before merge

### ISSUE THREAD

**Issue by gabrielsohn** [FMS-by-Conexoes-Games/discord-server#15]
Can you check my code and changes? its working but i want to know if im handling right with errors and stuff. Also optimize something if possible.

**Comment by gabrielsohn** [comment]
Also can you check things about language? i will need to use translation that i dont know how, and about autoDestroy, isnt good to set idk 48 hours to give the points or 1 week maybe? that date is in milliseconds? And we can trigger an event like beforeDestroy, to maybe deal with that message?

**Comment by eduardozgz** [comment]
The time left of autoDestroy is in milliseconds, about beforeDestroy... do you need it right now?

**Comment by eduardozgz** [comment]
Do a PR and assign me as reviewer please
