### ISSUE TITLE
Please, verify this text for orthograph 

### ISSUE THREAD

**Issue by Nikkijorie** [FMS-by-Conexoes-Games/discord-server#3]
Playcoins es una moneda virtual que puede ser intercambiada por periféricos, tarjetas de regalo, ¡y entre otras muchas cosas más! Accede a este canal para ver los productos disponibles: <#685155748271095857>

En partidas con más de 70 jugadores puedes ganar playcoins, pero debes enviar una captura de pantalla demostrando de que usas el código de creador **FMSSA** en la tienda Fortnite.

Playcoins Open
1er lugar - 3 playcoins
2do lugar - 2 playcoins
3er lugar - 1 playcoin

Playcoins Trial / Pro
1er lugar - 4 playcoins
2do lugar - 3 playcoins
3er lugar - 2 playcoins

¡También puedes recibir playcoins boosteando nuestro servidor, ve a <#688799519420317743>

Para intercambiar playcoins por productos, comuníquate con <@462009680252633118>!

**Comment by eduardozgz** [comment]
@Nikkijorie [I've sent it](https://discordapp.com/channels/422981185673625600/685155745074905104/695780279540777053), but I didn't include all the text since most of it was already available in the playcoins spanish channel
