### ISSUE TITLE
Can you please check this text for ortograph?

### ISSUE THREAD

**Issue by Nikkijorie** [FMS-by-Conexoes-Games/discord-server#6]
APOYÉ FMSSA

__**¿Quieres ayudar a FMS a crecer? Use nuestro código de creador en la tienda fortnite!**__

Apoyándonos usted puede:

- Publica tu historia en nuestro instagram (solo envíe una impresión en nuestro dm usando el código de creador)!
[INSTAGRAM](https://instagram.com/scrimsfms)

- ¡Puedes recibir playcoins para scrims con más de 70 jugadores!

Preguntas? Comuníquase con <@351854446780612609>
__________________________________________________________________________________________________________
In english:
SUPPORT FMSSA

Wanna help FMS to grow? Use our creator code on fortnite store! 

Using our code you can:
- share your storys on our instagram (u have to send a printscreen on our dm using our creator code

- can recieve playcoins for scrims with more than 70 players.

Questions? Contact Nikkis

**Comment by eduardozgz** [comment]
APOYA FMSSA

¿Quieres ayudar a FMS a crecer? ¡Usa nuestro código de creador en la tienda fortnite!

Apoyándonos podras:
• ¡Publicar tus historias en nuestro Instagram! (debes enviar una captura de pantalla a nuestro MD demostrando que usas el código de creador)
INSTAGRAM

• ¡Recibir playcoins en scrims con más de 70 jugadores!

Dudas? Contacta con <@351854446780612609>
